// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://moebuhqkwvpfcpsxmvuc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vZWJ1aHFrd3ZwZmNwc3htdnVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI4MTg3NTIsImV4cCI6MjA4ODM5NDc1Mn0.p7QJkDE6TxKhpnjo7gl5ylfrQuMDLCR0sEHcIfyga0c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});